### ISSUE TITLE
Demo 和 SDK不通

### ISSUE THREAD

**Issue by kai-db** [coming-chat/coming-web3view-android#4]
使用 implementation 'com.github.coming-chat:coming-web3view-android:1.0.1' ;

无法链接钱包，请问下这个是什么导致的？

       mWeb3View?.chainId = 1;
        mWeb3View?.setRpcUrl("https://mainnet.infura.io/v3/30c277db0eaa4085ac32ced784bc9af9");
        mWeb3View?.setWalletAddress(Address("0xaa3cc54d7f10fa3a1737e4997ba27c34f330ce16"));
        mWeb3View?.setUserInfo(UserInfo("10001","https://mainnet.infura.io/v3/30c277db0eaa4085ac32ced784bc9af9","0xaa3cc54d7f10fa3a1737e4997ba27c34f330ce16"))

        findViewById<Button>(R.id.go).setOnClickListener {
            val message = findViewById<EditText>(R.id.url).text.toString()

            mWeb3View?.loadUrl(message)

        }

        mWeb3View?.setOnConnectListener {
            Toast.makeText(this, "connect", Toast.LENGTH_LONG).show()
        }
        mWeb3View?.setOnSignMessageListener { message ->
            Toast.makeText(this, "OnSignMessag", Toast.LENGTH_LONG).show()
        }
        mWeb3View?.setOnSignPersonalMessageListener { message ->
            Toast.makeText(this, "OnSignPersonalMessage", Toast.LENGTH_LONG).show()
        }
        mWeb3View?.setOnSignTransactionListener { transaction, url ->
            Toast.makeText(this, "OnSignTransaction", Toast.LENGTH_LONG).show()
        }

**Comment by imtianx** [comment]
推荐使用 [trustwallet 实现的 provider ](https://github.com/trustwallet/trust-web3-provider)。
